services:
  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    restart: unless-stopped
    environment:
      - TZ=Europe/Moscow
      - CLOUDFLARED_TOKEN=${CLOUDFLARED_TOKEN}
    command: tunnel --no-autoupdate run --token ${CLOUDFLARED_TOKEN}
    networks:
      - cloudflared

networks:
  cloudflared:
    name: cloudflared
    external: true
