services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: always
    ports:
      - "9443:9443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /containers/portainer:/data
    networks:
      - cloudflared

networks:
  cloudflared:
    external: true
