services:
  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    restart: unless-stopped
    environment:
      - TZ=Europe/Moscow
    volumes:
      - /var/log:/var/log
      - /containers/loki:/loki
    command: -config.file=/etc/promtail/config.yml
    networks:
      - grafana

  loki:
    image: grafana/loki:latest
    container_name: loki
    restart: unless-stopped
    environment:
      - TZ=Europe/Moscow
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - grafana
      - cloudflared

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - TZ=Europe/Moscow
    entrypoint:
      - sh
      - -euc
      - |
        mkdir -p /etc/grafana/provisioning/datasources
        cat <<EOF > /etc/grafana/provisioning/datasources/ds.yaml
        apiVersion: 1
        datasources:
        - name: Loki
          type: loki
          access: proxy
          orgId: 1
          url: http://loki:3100
          basicAuth: false
          isDefault: true
          version: 1
          editable: false
        EOF
        /run.sh
    networks:
      - grafana
      - cloudflared

networks:
  grafana:
    name: grafana
  cloudflared:
    name: cloudflared
    external: true
